#-------------------------------
# General Site Settings
title: PT's Blog
logo: '/images/logos/logo.svg' # You can add own logo. For example '/images/logo.png'.
#description: ☐☐☐☐☐，☐☐☐☐☐☐。
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://blog.tomori.io/" # The base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Mortalreminder PT
  avatar: 'https://q.qlogo.cn/headimg_dl?dst_uin=2656453168&spec=140&img_type=jpg' # '/images/logos/avatar128.png'

#-------------------------------
# Hero Settings
hero:
  title: PT's Blog
  description: videtis illam spirare libertatis auram.
  image: 'https://bing.biturl.top/?resolution=1920&format=image&index=0&mkt=en-US'


#-------------------------------
# Contact Settings
contact:
  email: mail@mortalreminder.net # Add your email for contact form
  description: 非常欢迎您与博主联系！如果您对博客有任何建议，可以留言给博主来信，无论您是有疑问、需要帮助还是想表达对博主的赞赏，博主非常期待听到您的声音。

paginate: 8
paginate_path: "/page/:num"

# NOTE
# Norlin theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
#- {icon: "ion-logo-twitter", link: "https://twitter.com/Mortalreminder PTok"}
#- {icon: "ion-logo-facebook", link: "https://www.facebook.com/braianagustin.diez"}
- {icon: "ion-md-mail", link: "mailto://mail@mortalreminder.net"}
- {icon: "ion-logo-github", link: "https://github.com/MortalreminderPT"}
#- {icon: "ion-logo-instagram", link: "https://www.instagram.com/elblogdebraian"}

#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: n00b2h4ck3r # Add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
#google-analytics: UA-176116253-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp-identifier: https://app.us20.list-manage.com/subscribe/post?u65e25d0a60609c8cbde82c607;id=4eaddf4109 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/fontawesome/svg
  - jekyll-archives
  - jekyll-t4j

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
#tag_page_dir:         tag
#tag_page_layout:      tag_page
#tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed

# categories

# 访问
jekyll-archives:
  enabled: [categories, tags]
  layouts: archive
  permalinks:
#    year: '/archive/:year/'
#    month: '/archive/:year/:month/'
#    day: '/archive/:year/:month/:day/'
    tag: 'tags/:name/'
    category: 'categories/:name/'

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

color:
  82deg
# 时区
#timezone: Asia/Shanghai

# i18n
languages: ["en", "zh-cn"]